services:
  fastapi_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    # image: python:3.14-rc
    # container_name: amcp
    restart: always
    ports:
      - "9099:9099"
      - "5678:5678"
    # environment:
    #   - APP_ENV=production
    volumes:
      - /app/logs/:/opt/app/logs/
    # depends_on:
    #   - db
    networks:
      - my - network
    dns:
      - 8.8.8.8
      - 8.8.4.4
  fastapi_mcp_https:
    build:
      context: .
      dockerfile: Dockerfile_9449
    # image: python:3.14-rc
    # container_name: amcp
    restart: always
    ports:
      - "9449:9449"
    # environment:
    #   - APP_ENV=production
    volumes:
      - /app/logs/:/opt/app/logs/
    # depends_on:
    #   - db
    networks:
      - my - network
    dns:
      - 8.8.8.8
      - 8.8.4.4
#   db:
#     image: postgres:14
#     container_name: postgres - container
#     environment:
#       - POSTGRES_PASSWORD=eMHk1x6wDb81PiHw
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#     volumes:
#       - postgres - data:/var/lib/postgresql/data
#     networks:
#       - my - network

# volumes:
#   postgres - data:

networks:
  my - network: